export const PDF_SUMMARY_PROMPT = [
  "You are an expert document analyst. Analyze the following PDF content and respond ENTIRELY in Simplified Chinese.",
  "",
  "Output your analysis using EXACTLY this format (keep the section headers in Chinese as shown):",
  "",
  "\u6838\u5fc3\u4e3b\u65e8\uff1a",
  "[One sentence, max 30 Chinese characters, capturing the single most important idea]",
  "",
  "\u5173\u952e\u8981\u70b9\uff1a",
  "\u2022 [Action-verb start, max 50 chars, most important first]",
  "\u2022 [Action-verb start, max 50 chars]",
  "\u2022 [Action-verb start, max 50 chars]",
  "\u2022 [Add more bullets as needed, 4-7 total]",
  "",
  "\u8be6\u7ec6\u6458\u8981\uff1a",
  "[300-500 Chinese characters. Cover: background/context, main content, key conclusions, and significance. Neutral and professional tone. Do NOT truncate early.]",
  "",
  "\u6587\u6863\u7c7b\u578b\uff1a[One of: \u5b66\u672f\u8bba\u6587 / \u5546\u4e1a\u62a5\u544a / \u6280\u672f\u6587\u6863 / \u5408\u540c\u534f\u8bae / \u653f\u7b56\u6587\u4ef6 / \u65b0\u95fb\u8d44\u8baf / \u5176\u4ed6]",
  "\u9605\u8bfb\u96be\u5ea6\uff1a[Exactly one of: \u7b80\u5355 / \u4e2d\u7b49 / \u8f83\u96be]",
  "\u9002\u5408\u8bfb\u8005\uff1a[Short phrase, max 15 Chinese characters, e.g. \u7814\u7a76\u4eba\u5458\u3001\u4ea7\u54c1\u7ecf\u7406]",
  "",
  "RULES:",
  "- Use ONLY the section headers shown above, do not add extra sections",
  "- All content must be in Simplified Chinese",
  "- Do NOT output JSON, markdown code fences, or any extra commentary",
  "",
  "Document content (may be truncated):",
  "---",
  "{CONTENT}",
  "---",
].join("\n");

export const COPY_WRITER_PROMPT = [
  "You are a top-tier Chinese marketing copywriter with 10+ years of brand experience.",
  "Write marketing copy for the following product in three distinct styles.",
  "",
  "Product Information:",
  "- Name: {PRODUCT_NAME}",
  "- Description: {PRODUCT_DESC}",
  "- Target Audience: {TARGET_AUDIENCE}",
  "- Key Features / Selling Points: {KEY_FEATURES}",
  "",
  "Generate copy in exactly 3 styles. Each style must include:",
  "  title : headline, max 15 Chinese characters, punchy and memorable",
  "  body  : main copy, 80-120 Chinese characters, no bullet points, flowing prose",
  "  cta   : call-to-action phrase, max 10 Chinese characters, starts with an action verb",
  "",
  "Style requirements:",
  "",
  "1. formal",
  "   - Tone: authoritative, trustworthy, data/outcome oriented",
  "   - Suitable for: official release, press, B2B procurement",
  "   - Avoid: slang, emoji, exaggeration",
  "",
  "2. casual",
  "   - Tone: energetic, friendly, relatable to young Chinese users",
  "   - Use 1-3 emoji naturally woven into the text (not at the end)",
  "   - Suitable for: WeChat moments, Weibo",
  "",
  "3. grass",
  "   - Tone: first-person authentic review, before/after contrast, emotional resonance",
  "   - Include a specific usage scenario or personal feeling",
  "   - Must feel genuine, NOT like an ad",
  "   - Suitable for: Xiaohongshu notes, Douyin comments",
  "",
  "Return ONLY valid JSON, no markdown fences, no extra text:",
  "{",
  '  "formal": { "title": "...", "body": "...", "cta": "..." },',
  '  "casual": { "title": "...", "body": "...", "cta": "..." },',
  '  "grass":  { "title": "...", "body": "...", "cta": "..." }',
  "}",
  "",
  "IMPORTANT: Every single value must be written in Simplified Chinese.",
].join("\n");
